### ISSUE TITLE
wrong url in readme

### ISSUE THREAD

**Issue by vsaase** [mathworks-ref-arch/matlab-rabbitmq#3]
`git clone --recursive https://github.com/mathworks-ref-arch/mathworks-rabbitmq.git`

should be

`git clone --recursive https://github.com/mathworks-ref-arch/matlab-rabbitmq.git`

**Comment by jeffhuang2019** [comment]
thank you and we will fix in the next release.

**Comment by maben-mw** [comment]
This is fixed
