### ISSUE TITLE
Can this be used in the absence of production server?

### ISSUE THREAD

**Issue by jerlich** [mathworks-ref-arch/matlab-rabbitmq#7]
If I want to just connect Matlab to an a rabbitMQ server, can I use this library?

**Comment by jeffhuang2019** [comment]
Hi, Jeffrey,

Thanks so much for your review and feedback on the MATLAB-RabbitMQ package. We only support the RabbitMQ integration with MATLAB Production Server via HTTP POST at this point. But please feel free to reach out to us if you have any other questions.

Thanks,
Jeff from MathWorks

**Comment by maben-mw** [comment]
We have published a new version of the package v0.2.0 which does now add a [MATLAB interface](https://github.com/mathworks-ref-arch/matlab-rabbitmq/blob/b4123c710a0fa970ec1476515ee17b7e1f82dd1c/Documentation/MATLABInterface.md) for RabbitMQ.
