### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by rose-1-0** [mathworks-ref-arch/matlab-rabbitmq#9]
Hello, I encountered an error while installing the warehouse. I think there may be some problems with your directory

[ERROR] Unknown lifecycle phase "\". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]

**Comment by maben-mw** [comment]
The error you receive there would be thrown if you run mvn with an empty input:
```
mvn ""
```
But I do not believe any of the instructions includes running mvn in such a way and I am not immediately aware of any other situations which would throw this error. I am also not entirely sure which exact step you refer to when you say that this occurs "while installing the warehouse".

1. Which exact step of the instructions are you at?
2. What is the exact full command you were trying to run?
3. What is the _full_ output produced by running that command?

**Comment by maben-mw** [comment]
We have published a new version of the package v0.2.0 which changes the installation process somewhat. I suspect this will resolve any installation issue you may have had before and I am tentatively closing the issue. Please do submit a new issue if you still see an issue with the updated package.
